### ISSUE TITLE
Customizability of appearance

### ISSUE THREAD

**Issue by UltimateDavid** [Isopolito/gNordVPN-Local#18]
Great work Isopolito on this extension. I have one request though.
On my screen, it is quite prominent at the moment and I think it would really benefit from a few customizability options. 

First of all: I think it would be nice to include a switch or something to 'minimize' it. 
so to go from this:
![image](https://user-images.githubusercontent.com/40173158/148757569-7fa843f7-7024-4703-bc7e-6bea052aaa83.png)
To one of these options:
![vpnheading](https://user-images.githubusercontent.com/40173158/148759797-edfac3ef-0a14-48aa-ab08-2071e988fe14.png)
You do have to make sure though that when you click it, the server and status would still be visible in the dropdown.

Secondly, a Monochrome option (where its for example a white box with black text for example), would also be cool. 
![image](https://user-images.githubusercontent.com/40173158/148760563-08a49deb-13ce-40e8-8166-5992cd555f64.png)
But again, I think this is quite prominent, so a minimized version could help clean it up. 

Just some thoughts, let me know what you think!

**Comment by Isopolito** [comment]
Sorry @UltimateDavid, just now seeing this issue. I agree 100% and have been thinking about doing just that for a future release. I like your suggestions even better than what I was originally planning, so thank you! And feel free to open a PR if you already have something in place.

**Comment by Isopolito** [comment]
@UltimateDavid, newest version of the extension has most of your requested features, icon support coming in the future...thanks for the feedback

**Comment by Isopolito** [comment]
Closing issue, only thing missing from the initial request is icon support.
