### ISSUE TITLE
Compatibility with GNOME 4

### ISSUE THREAD

**Issue by UltimateDavid** [Isopolito/gNordVPN-Local#19]
Sadly, this extension is not compatible with GNOME 4.
![image](https://user-images.githubusercontent.com/40173158/149520987-e2002172-7b6d-4d89-ae63-daca17ed43e5.png)

**Comment by Isopolito** [comment]
@UltimateDavid I just submitted a new version to gnome extensions. It's to upgrade the extension to the latest gnome versions. It also includes a new settings dialog enhancement and some bug fixes. It should be available within a day or two. Thanks for the feedback! Cheers

**Comment by Isopolito** [comment]
Released new version that works with GNOME 4
