### ISSUE TITLE
Compatibility with Ubuntu 22.04 - Gnome-Shell 42.1

### ISSUE THREAD

**Issue by kevinmarchant** [Isopolito/gNordVPN-Local#23]
I'm looking at upgrading to Ubuntu 22.04 in the near future and have been trying to get your shell extension to work.

Unfortunately gnome-shell-extension-prefs flags it was "The extension is incompatible with the current GNOME version."

Was compatibility with the latest LTS release of Ubuntu something you could look at please.

**Comment by Isopolito** [comment]
Hi @kevinmarchant, going to take a look right now. Thanks for bringing this up

**Comment by Isopolito** [comment]
@kevinmarchant, v10 has been released. It's now compatible with gnome 41 and 42. Thanks for bringing this to my attention.

**Comment by kevinmarchant** [comment]
Many thanks!  Works a treat!
