### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by jlnxr** [Isopolito/gNordVPN-Local#30]
This extension works great! However, the colour is either an awful looking bright red, or an equally awful looking green. Both are kind of eye-shearing and not something I want on my Gnome panel. I'm using a different extension in the mean time but it is less fully featured than this one. Ideally the user could pick the colours, or a monochrome option fitting in with the rest of the panel would be used. 

Thanks!

**Comment by Isopolito** [comment]
Hi @jlnxr, what version are you currently using? The newest version allows for color selection

**Comment by Isopolito** [comment]
Closing issue since this functionality exists in the newest version of the extension.
