### ISSUE TITLE
Disable extension is not working for gnome 43

### ISSUE THREAD

**Issue by makarov-roman** [Isopolito/gNordVPN-Local#33]
**Describe the bug**
When I tried to disable extension via Extensions app it showed following error: 
`this._commonFavorite.disable is not a function`

**To Reproduce**
1. Go to `Extensions` app
2. Click on 'on/off switch'
3. See error

**Expected behavior**
Extension is disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/11902307/192151595-a002eb84-4988-4f41-9b8f-98048780d243.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37

**Additional context**
Gnome Extensions version: 43~beta from fedora repo.
I don't know how are pipelines for plugin release working, but the latest available version at [gnome-extensions](https://extensions.gnome.org/extension/2569/gnordvpn-local/) is 11 (should be 12).

**Comment by Isopolito** [comment]
Hi @makarov-roman, thanks for the heads up on this and the details you provided. Looking into it now, still haven't released version 12 to gnome extensions because I need to get a VM with gnome 43 loaded up to test

**Comment by Isopolito** [comment]
@makarov-roman I can reproduce the error, going to get a fix out next week and will release version 12 of the extension

**Comment by Isopolito** [comment]
@makarov-roman
