### ISSUE TITLE
Text not centered in icon

### ISSUE THREAD

**Issue by jvanheugten** [Isopolito/gNordVPN-Local#36]
**Describe the bug**
Text not centered in the dock icon (for any style).

**To Reproduce**
Just installed it.

**Expected behavior**
Centered text in dock.

**Screenshots**
![image](https://user-images.githubusercontent.com/12444498/197780624-0cdb1ddd-e86c-4c86-a3ac-5364f99b0f37.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS, Gnome 42.4
 - Browser: Chrome

**Additional context**

**Comment by Isopolito** [comment]
Hi @jvanheugten, thanks for bringing this up. What resolution are you using?  I noticed you mentioned it's not centered for any style? Does that mean you've tried configuring things manually here?
![image](https://user-images.githubusercontent.com/13524742/198073486-4c9067ab-52af-4635-a519-b20b6d4f2aec.png)

If that didn't work, i'll see if I can replicate it by changing my resolution to what you have. Are you using wayland?

i'm slammed right now at my day job but will work on this as soon as I get the opportunity. Thanks

**Comment by Isopolito** [comment]
Hi @jvanheugten , any updates on the above?

**Comment by jvanheugten** [comment]
Sorry, I'm traveling at the moment, next week I'll be back.
Resolution is fairly large, but don't know it off the top of my head (i think 2560x1440).
I've only tried the small to extra large buttons.
Didn't change the css styling further.
I'm not using Wayland.

**Comment by Isopolito** [comment]
No worries! I'll see if I can repro with different resolutions and go from there. The CSS of the extension is pretty customizable now, so you might be able to fix it through css tweaks in the settings

**Comment by Isopolito** [comment]
Hi @jvanheugten anything new to report on this?

**Comment by jvanheugten** [comment]
The resolution was 2560x1440. I fixed it by changing the padding to `padding 0px 10px`

**Comment by Isopolito** [comment]
Awesome @jvanheugten, thanks for the update!
