### ISSUE TITLE
"status.currentServer is undefined" Error

### ISSUE THREAD

**Issue by DarylO71** [Isopolito/gNordVPN-Local#38]
I am running version 11 on Ubuntu 22.04, and this extension no longer runs for me.  I cannot re-enable it, and I'm getting a "status.currentServer is undefined" error message in the extension selection app.  This extension was working just fine a couple of days ago.  I've rebooted and restarted GNOME Shell multiple times as well as removed and reinstalled the extension, but nothing has helped.

Daryl

**Comment by Isopolito** [comment]
Okay interesting, I will take a look and try to replicate this behavior. The day job is keeping me busy right now so I might not get to it until this weekend. I'll update here as I find things. Thanks for putting this on my radar

**Comment by DarylO71** [comment]
@Isopolito No problem.  I appreciate your looking into this.  By the way, my NordVPN version is 3.15.1.

**Comment by Isopolito** [comment]
Reproduced the issue, thanks @DarylO71

**Comment by DarylO71** [comment]
@Isopolito By the way, when the extension does work, there is always a problem with the settings screen: one doesn't see anything until one scrolls up.  I could open another bug if you'd like (once you fix this one).

**Comment by Isopolito** [comment]
Thanks @DarylO71, I know exactly what you're talking about, I'll fix that along with this

**Comment by Isopolito** [comment]
@DarylO71 Fix for this will be released today, thanks again!

**Comment by Isopolito** [comment]
@DarylO71 Forgot to mention, the scroll issue on the prefs window is a GTK thing, going to have to dig deep to figure out that one. Creating a separate issue for that. Cheers

**Comment by DarylO71** [comment]
@Isopolito Thanks, Austin!  I'll be looking forward to the release.  With regard to the scroll issue, I haven't noticed a similar problem with other extensions.  Is it possible that you just need to specify a smaller window size?

**Comment by Isopolito** [comment]
Hi @DarylO71, your suggestion is a good one and something I definitely will be trying next chance I get to work on this
