### ISSUE TITLE
Prefs window opens up with content scrolled to bottom

### ISSUE THREAD

**Issue by Isopolito** [Isopolito/gNordVPN-Local#40]
Talked with someone from the gnome extensions team, they believe it's a GTK issue. Need to dig deeper, ask that channel on element.

**Comment by Isopolito** [comment]
I believe the best approach is to switch from using the older "buildPrefsWidget" (in prefs.js) style to using [Adw](https://gjs.guide/extensions/development/preferences.html#preferences-window)

**Comment by jvalecillos** [comment]
I can confirm the bug. Also the window is too large horizontally, more than the laptop screen even and it is not resizable to less than that. It should be possible to wrap the content somehow.

**Comment by Isopolito** [comment]
Thanks @jvalecillos, I agree and I'll keep that in mind when I get a chance to work on this. Cheers!
