### ISSUE TITLE
Favorite Server

### ISSUE THREAD

**Issue by fromthecove** [Isopolito/gNordVPN-Local#44]
**Describe the solution you'd like**
Be able to star the current server as a "Favorite Server" for quick reconnects.

**Additional context**
NordVPN's dedicated IP address feature reserves a dedicated IP for a NordVPN account, and that IP is available on only a single server.  Any time a user with a dedicated IP connects to that specific server, e.g., US#6697, they receive the dedicated IP.  Being able to mark a specific server as a favorite for quick reconnects would be a great help to users paying for a dedicated IP.

I can see in the extension's default config schema a place for favorite servers:

```       
<key name="favorite-servers" type="s">
    <default>""</default>
</key>
```

... but I have yet to figure out how (or if it's possible to) mark a server as a favorite in the extensions GUI.

**Comment by dlowhorn** [comment]
**My Current Work Around**

- Copy default org.gnome.shell.extensions.gnordvpn-local.gschema.xml to $HOME/.share/local/glib-2.0/schemas
- cd $HOME/.share/local/glib-2.0/schemas && glib-compile-schemas .

This adds the **favorite-servers** key to the settings as found in dconf editor. From there I can manually add a JSON string as the value, e.g., {"us4981":"us4981"}.  Then, with the the **commonfavorite** value turned on the extension will show us4981 in the common favorites list.  

My conclusion:  either this feature was included at one point but removed from the GUI, or is under development, or there's some way of marking a server as a favorite that I haven't found yet in the current GUI.

**Comment by Isopolito** [comment]
Hi @fromthecove, 

I just made a change that I will merge to main shortly that auto connects to last selected connection. There is already the ability to start favorite servers in the Server menu. 
![image](https://github.com/Isopolito/gNordVPN-Local/assets/13524742/f0cc5c54-32a9-40c0-9a08-a9e6b08e620a)

So you can have dedicated servers starred, and when you select one--that will be the one that is always connected to by default. I believe this will satisfy you requirements, correct?
