### ISSUE TITLE
Choose country for autoconnection

### ISSUE THREAD

**Issue by RyanOrigens** [Isopolito/gNordVPN-Local#52]
**Is your feature request related to a problem? Please describe.**
I set the autoconnection on but every single time it picks a random country

**Describe the solution you'd like**
An option to pick the country for autoconnection

**Describe alternatives you've considered**
Pick always the fastest connection (I think it might be already doing it, some reason it doesn't work properly for me tough)

I also wanted to mention a bug that is annoying me, it is occurring only on gnome 44, i haven't tested that much tough there is not how to be sure, but every time i try to open the pop up on the tray it lags my computer a bit and sometimes i even have to reboot (I'm using X11 not sure about wayland tough)

**Comment by Isopolito** [comment]
@RyanOrigens  I'm working on the extension again. Can you tell me more about this issue. For instance, when you try to open the pop up on the tray. What do you mean by that exactly?

And for the autoconnection issue, I can't replicate this. Can you give me some more details. Is that after login? Reboot? Log in of the nordvpn?

Thanks

**Comment by RyanOrigens** [comment]
Apologies for the delayed response,

I have just reinstalled the extension to test it again. I am running it under x11/gnome 44, and when I clicked on the pop-up to choose a country, it caused my computer to freeze, requiring a reboot. Additionally, the pop-up itself seems to open slower than others.

What I experienced was that it was randomly selecting a country, not remembering the last country I was logged into. It would be beneficial if you could add an option to select the fastest country, or even better, to manually specify a country. Unfortunately, I can't provide more specific details as I've encountered multiple crashes with this extension.

**Comment by Isopolito** [comment]
Hi @RyanOrigens ,

I made some updates that are in master now so that the most recently used connection is what's set to auto connect. This should take care of part of your request.

As for the stability issues, I know what's happening. It's just difficult to fix--it's a work in progress.

**Comment by RyanOrigens** [comment]
Thank you!

**Comment by Isopolito** [comment]
You're welcome, I'll be continuing to push changes to master. By the next official release of the extension I plan on having some of the stability issues ironed out.
