### ISSUE TITLE
Fedora 39 Support

### ISSUE THREAD

**Issue by goldentg** [Isopolito/gNordVPN-Local#82]
Was easily my favourite part of fedora 38 and was sad to see that it isnt supported in 39 yet

**Comment by Isopolito** [comment]
Hi @goldentg, glad to hear you like it. I'm currently in the process of updating for gnome 45. It's pretty close to done. In the meantime you can install from this [branch](https://github.com/Isopolito/gNordVPN-Local/tree/Gnome45)

Cheers

**Comment by Isopolito** [comment]
@goldentg  gnome 45 version of the extension released
