### ISSUE TITLE
With Dash to Panel, the icon is much bigger

### ISSUE THREAD

**Issue by NelsonH75** [Isopolito/gNordVPN-Local#86]
**Describe the bug**

**To Reproduce**
1. Use Dash to Panel
2. Use gNordVPN-Local
3. View "tray"
4. Result is screenshot attached
![Screenshot from 2024-02-13 01-50-43](https://github.com/Isopolito/gNordVPN-Local/assets/78701753/ba1a0cd6-1fa6-4c45-b457-541e5b1d232a)

**Expected behavior**
It to not look weird (Button is too wide). Small CSS thing/

**Screenshots**
![Screenshot from 2024-02-13 01-50-43](https://github.com/Isopolito/gNordVPN-Local/assets/78701753/ba1a0cd6-1fa6-4c45-b457-541e5b1d232a)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Browser Firefox

**Additional context**
Not sure if this counts as a bug (I'm assuming there's a conflict with dash to panel), its a minor thing, but just thought be worth putting here.

**Comment by Isopolito** [comment]
Hi @NelsonH75,

Thanks for the feedback? Have you tried adjusting the styling of the extension as a work around?

**Comment by DarthRidar** [comment]
I have the same problem. It is much larger than the others. It's not in the panel. You can see it even better in Open Bar.

![Bildschirmfoto vom 2024-03-23 08-09-32](https://github.com/Isopolito/gNordVPN-Local/assets/98944937/edb650fd-c0db-4f4e-b0f4-2b52d51262e3)

![Bildschirmfoto vom 2024-03-23 08-09-45](https://github.com/Isopolito/gNordVPN-Local/assets/98944937/3562d489-11a3-4a0d-8678-e9563441a57f)

**Comment by NelsonH75** [comment]
Thanks @Isopolito ,
That worked, and now it's not unbearably large

**Comment by Isopolito** [comment]
Awesome  to hear @NelsonH75 ! If you get it looking good would you mind posting the css you used so I can add some notes to the documentation for others that may have this issue?

Or even better feel free to PR an update the to the docs yourself with what you did and the css you used.

Thanks

**Comment by NelsonH75** [comment]
Common CSS: font-weight: bold; border-radius: 20px; padding: 12px 11px 0; margin: 6px 0px 5px 05px; 

thats literally it, just tinkered the values til it worked.

**Comment by NelsonH75** [comment]
> Common CSS: font-weight: bold; border-radius: 20px; padding: 12px 11px 0; margin: 6px 0px 5px 05px;
> 
> thats literally it, just tinkered the values til it worked.

![image](https://github.com/Isopolito/gNordVPN-Local/assets/78701753/366771a8-c41c-4bfd-b147-a5ddb8321511)
^What it looks like now

**Comment by Isopolito** [comment]
Thanks, I'll update the docs
