### ISSUE TITLE
Appearing at the top, before the settings menu on GNOME!

### ISSUE THREAD

**Issue by RyanOrigens** [Isopolito/gNordVPN-Local#91]
Add an option to allow users to choose the location, or simply place it in the second spot rather than the first.

![image](https://github.com/Isopolito/gNordVPN-Local/assets/103891807/6c5ae910-5455-4faf-9508-93f43d7561d5)

**Comment by Isopolito** [comment]
Hi @RyanOrigens, there's this setting that allows it to be moved to left, right, and center positions. Is this what you had in mind or are you referring to the order in which it appears relative to the other extensions?

![image](https://github.com/Isopolito/gNordVPN-Local/assets/13524742/12987111-199a-4113-8bd5-8daaf8830305)

**Comment by RyanOrigens** [comment]
I mean the order it appears relative to the other extensions... The only problem here is that it is getting behind the first element (Power Menu). Also, I'm unable to reorder it using ORDER GNOME SHELL EXTENSION, as it doesn't show up as a tray element.

**Comment by Isopolito** [comment]
Not familiar with that extension, I just checked it out. It doesn't recognize another one of my other extensions I use, not sure what's going on there.

I've always used an executable bash script that I run on gnome login for bootstrapping and configuring certain things programmatically. I call it xstartup. At the end of the script I have this:

```
# Turn off and on again the extensions that should be at end
(sleep 1 && gnome-extensions disable keyboard_modifiers_status@sneetsher && gnome-extensions enable keyboard_modifiers_status@sneetsher)&
(sleep 1 && gnome-extensions disable tophat@fflewddur.github.io && gnome-extensions enable tophat@fflewddur.github.io)&
```

Which I use to dictate the order of certain extensions.

To cause the xstartup script run on login I have this:  ~/.config/autostart/gnome_login.desktop whose contents are as follows:

```
[Desktop Entry]
Type=Application
Exec=/home/USERNAME/bin/xstartup
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Gnome Login Script
Comment=Configure gnome post login
```

Not exactly what you're looking for, but it could be a work around. 

To solve this issue I would have to dig into that other extension's source code figure out why it's not recognizing certain types of extension. It could be an issue with gnordvpn or it might be an issue on their end, they might not recognize certain types of extensions.

Realistically I'm going to get a chance to do that for a while, if ever. If you know a bit of JS, I recommend trying to research this and see if you can come up with a fix.
