### ISSUE TITLE
Cities and Servers are not displayed

### ISSUE THREAD

**Issue by natsume42** [Isopolito/gNordVPN-Local#93]
**Describe the bug**
Cities and Servers are not displayed—neither in settings dialog, nor in the main menu.
Besides that, the extension and nordvpn are working fine, e.g. I am able to do a connect and the state (along with status details are shown as expected).

**To Reproduce**
a. Open Cities or Servers tab in settings dialog.
b. Open extension menu.

**Expected behavior**
a. The list of cities/servers should be populated according to nordvpn’s output.
b. dito.

**Screenshots**
![Screenshot from 2024-05-27 18-13-59](https://github.com/Isopolito/gNordVPN-Local/assets/81567228/04be661b-c227-4ec3-94a5-79c25b42bae6)

**Desktop (please complete the following information):**
 - OS: Debian 12 
 - DE: Gnome

**Additional context**
- For instance, I can do a `nordvpn c double_vpn` from shell, but the extension does not offer this option to me.
- `nordvpn groups`:
```
Africa_The_Middle_East_And_India	Double_VPN				P2P
Asia_Pacific				Europe					Standard_VPN_Servers
Dedicated_IP				Onion_Over_VPN				The_Americas
```

**Comment by Isopolito** [comment]
Hi @natsume42 , I just double checked on my machine and Cities/Servers is working. What versions of gnome and nordvpn cli are you using?

gnome-shell --version
nordvpn --version

**Comment by natsume42** [comment]
Thanks for the quick reply.

GNOME Shell 43.9
NordVPN Version 3.18.1

Any other information that I could provide? Is there a log or something?

**Comment by Isopolito** [comment]
HI @natsume42,

So the issue is that you're running an old version of the extension w/ a new version of nordvpn cli. Nordvpn CLI will change their output format sometimes and the extension code has to change to accommodate it. 

Whenever you upgrade gnome and get the latest version of the extension, things will work as expected again

**Comment by natsume42** [comment]
Thanks for the info.

I just upgraded debian to testing branch:
GNOME Shell 44.9
NordVPN Version 3.18.1

Still no luck: The lists are not populated.

Which Gnome Shell version is compatible with which nordvpn version?

**Comment by Isopolito** [comment]
Hi @natsume42, you're welcome. 

This version of the shell/extension works with the latest version of nordvpn:
![image](https://github.com/Isopolito/gNordVPN-Local/assets/13524742/77f544e7-af75-4daf-9f9d-c5745cc9b720)

I can't remember when the last time nordpvn cli output changed though, so the latest nordvpn cli version might also work with a couple of the prior extension version as well.

**Comment by natsume42** [comment]
I downgraded nordvpn to version 3.15.5. Here the lists get populated. Great.

But then I realized that I do not need countries/cities/servers, but I want to be able to do `nordvpn c double_vpn` which neither of the lists allow me to do. This is one of the options listed with `nordvpn groups`.

Groups are not handled by version 23 of the extension (for GNOME 44.9).

**Comment by ReveHavan** [comment]
I somewhat fixed it, although it's inelegant. All I did was to edit this function in ../modules/VPN.js
```
    // Remove the junk that shows up from messages in the nordvpn output
    _processCityCountryOutput = (input) => {
        input = input.replace("0m", ''); // Remove any leading junk
        input = input.replace("94m", ''); // Remove any leading junk
        input = input.replace(/[\W]+/, '\n'); // Remove any leading junk
        const countries = input.split('\n').map(c => c.trim()); // Split and trim each country name
        const validCountries = countries.filter(c => /\b\w[\w\s'-]*\b/.test(c)); // Keep valid country names
        return validCountries.sort(); // Sort and return the valid country names
    };
```
