### ISSUE TITLE
compatibility issue with open bar

### ISSUE THREAD

**Issue by paolocalosso** [Isopolito/gNordVPN-Local#99]
**Describe the bug**
i love [open bar gnome extension](https://github.com/neuromorph/openbar) and i love also gnordvpn-local extension! btw this doesn't seem to respect the top bar margin as shown in the attached screenshot

**To Reproduce**
1. install open bar extension and set top bar type to islands mode
2.  install gnordvpn-local extension
3. the gnordvpn-local icon borders in top bar seem "bigger" than expected

**Expected behavior**

**Screenshots**
![Screenshot from 2024-12-12 18-13-45](https://github.com/user-attachments/assets/3b34d124-5063-44d1-8eac-7e01d7681391)

**Desktop (please complete the following information):**
 - OS: ubuntu 24.04 and debian sid
 - Versions:

-  - gnordvpn-local: 29
-  - open bar: 41

**Comment by Isopolito** [comment]
Hi @paolocalosso, it's great to hear that you love the extension! I've never heard of open bar. I just installed and I like it, so thanks for putting it on my radar.

Have you played around with the gnordvpn settings? I didn't spend much time messing with it, but I see that left/center/right positioning is working with open bar
![image](https://github.com/user-attachments/assets/ca6bc667-5d1d-4d31-945a-952e7f181a3e)

You can also try manually tweaking the gnordvpn css to get a bit more control:
![image](https://github.com/user-attachments/assets/3b7d0c14-7fca-4aba-8b17-5fcd5f423eca)

**Comment by paolocalosso** [comment]
Hello, [neuromorph](https://github.com/neuromorph) (the creator of openbar extension)  solved the issue [here](https://github.com/neuromorph/openbar/issues/94).
![Screenshot from 2024-12-16 11-30-30](https://github.com/user-attachments/assets/fec5c88c-583b-48c7-9145-76e7bc5b1f76)

**Comment by Isopolito** [comment]
@paolocalosso thanks for the update, I'll incorporate in that code change, if there's no issues w/it, it'll go out with the next release. Cheers
